### PR TITLE
added Vietnamese

### PR DESCRIPTION
**Pull request by 34306**

### CODE REVIEW

**Comment by roothide** [comment]
Great!  thank you,  sorry we misspelled "SelectAll" as "SeleteAll", hope that didn't confuse you.  and "varClean" means cleaning junk files in /var/, maybe we should keep the word "var" after translation.

**Comment by lebao3105** [comment]
@34306 just have fixed varClean, SelectAll did not confuse him

**Comment by roothide** [comment]
image
@34306 could you please not submit files other than .lproj so that it can be automatically merged.

**Comment by 34306** [comment]
> image @34306 could you please not submit files other than .lproj so that it can be automatically merged.

Oh, that's Xcode automatically gen vi.lproj so that's Xcode references. Sorry about that

**Comment by roothide** [comment]
okay manually merged

**Pull request merged**
